---
- name: Issue systemctl daemon-reload to pick up config changes
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart the apt-daily timer
  ansible.builtin.systemd:
    name: apt-daily.timer
    state: restarted

- name: Restart the apt-daily-upgrade timer
  ansible.builtin.systemd:
    name: apt-daily-upgrade.timer
    state: restarted

- name: Reconfigure the unattended-upgrades package
  ansible.builtin.command:
    cmd: dpkg-reconfigure -f noninteractive unattended-upgrades
  changed_when: false
